/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '@angular/http/src/backends/browser_xhr';
import * as import10 from '@angular/http/src/base_response_options';
import * as import11 from '@angular/http/src/backends/xhr_backend';
import * as import12 from '@angular/http/src/base_request_options';
import * as import13 from '../../../src/app/app.backend.service';
import * as import14 from '@angular/core/src/application_init';
import * as import15 from '@angular/core/src/testability/testability';
import * as import16 from '@angular/core/src/application_ref';
import * as import17 from '../../../src/app/app.service';
import * as import18 from '@angular/common/src/localization';
import * as import19 from '@angular/core/src/linker/compiler';
import * as import20 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import21 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import22 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import23 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import24 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import25 from '@angular/core/src/animation/animation_queue';
import * as import26 from '@angular/core/src/linker/view_utils';
import * as import27 from '@angular/platform-browser/src/browser/title';
import * as import28 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import29 from '@angular/common/src/location/location';
import * as import30 from '@angular/router/src/url_tree';
import * as import31 from '@angular/router/src/router_outlet_map';
import * as import32 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import33 from '@angular/router/src/router_preloader';
import * as import34 from '../../../src/app/app.resolver';
import * as import35 from '@angular/core/src/di/injector';
import * as import36 from './home/home.component.ngfactory';
import * as import37 from './about/about.component.ngfactory';
import * as import38 from './no-content/no-content.component.ngfactory';
import * as import39 from './app.component.ngfactory';
import * as import40 from '@angular/core/src/i18n/tokens';
import * as import41 from '@angular/core/src/application_tokens';
import * as import42 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import43 from '@angular/platform-browser/src/dom/events/key_events';
import * as import44 from '@angular/core/src/zone/ng_zone';
import * as import45 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import46 from '@angular/common/src/location/platform_location';
import * as import47 from '@angular/common/src/location/location_strategy';
import * as import48 from '../../../src/app/home/home.component';
import * as import49 from '../../../src/app/about/about.component';
import * as import50 from '../../../src/app/no-content/no-content.component';
import * as import51 from '@angular/router/src/url_handling_strategy';
import * as import52 from '@angular/router/src/route_reuse_strategy';
import * as import53 from '@angular/router/src/router';
import * as import54 from '@angular/core/src/console';
import * as import55 from '@angular/core/src/error_handler';
import * as import56 from '@angular/http/src/interfaces';
import * as import57 from '@angular/http/src/http';
import * as import58 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import59 from '@angular/platform-browser/src/dom/animation_driver';
import * as import60 from '@angular/core/src/render/api';
import * as import61 from '@angular/core/src/security';
import * as import62 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import63 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import64 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import65 from '@angular/router/src/router_config_loader';
import * as import66 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _ErrorHandler_8:any;
  _BrowserXhr_9:import9.BrowserXhr;
  _ResponseOptions_10:import10.BaseResponseOptions;
  _XSRFStrategy_11:any;
  _XHRBackend_12:import11.XHRBackend;
  _RequestOptions_13:import12.BaseRequestOptions;
  _Http_14:any;
  _AppConfig_15:import13.AppConfig;
  _APP_INITIALIZER_16:any[];
  _ApplicationInitStatus_17:import14.ApplicationInitStatus;
  _Testability_18:import15.Testability;
  _ApplicationRef__19:import16.ApplicationRef_;
  _ApplicationRef_20:any;
  _AppState_21:import17.AppState;
  _AppModule_22:import1.AppModule;
  __LOCALE_ID_23:any;
  __NgLocalization_24:import18.NgLocaleLocalization;
  __Compiler_25:import19.Compiler;
  __APP_ID_26:any;
  __DOCUMENT_27:any;
  __HAMMER_GESTURE_CONFIG_28:import20.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_29:any[];
  __EventManager_30:import21.EventManager;
  __DomSharedStylesHost_31:import22.DomSharedStylesHost;
  __AnimationDriver_32:any;
  __DomRootRenderer_33:import23.DomRootRenderer_;
  __NgProbeToken_34:any[];
  __RootRenderer_35:any;
  __DomSanitizer_36:import24.DomSanitizerImpl;
  __Sanitizer_37:any;
  __AnimationQueue_38:import25.AnimationQueue;
  __ViewUtils_39:import26.ViewUtils;
  __IterableDiffers_40:any;
  __KeyValueDiffers_41:any;
  __SharedStylesHost_42:any;
  __Title_43:import27.Title;
  __RadioControlRegistry_44:import28.RadioControlRegistry;
  __ROUTER_CONFIGURATION_45:any;
  __LocationStrategy_46:any;
  __Location_47:import29.Location;
  __UrlSerializer_48:import30.DefaultUrlSerializer;
  __RouterOutletMap_49:import31.RouterOutletMap;
  __NgModuleFactoryLoader_50:import32.SystemJsNgModuleLoader;
  __ROUTES_51:any[];
  __Router_52:any;
  __ActivatedRoute_53:any;
  _PreloadAllModules_54:import33.PreloadAllModules;
  _PreloadingStrategy_55:any;
  _RouterPreloader_56:import33.RouterPreloader;
  __NoPreloading_57:import33.NoPreloading;
  __ROUTER_INITIALIZER_58:any;
  __APP_BOOTSTRAP_LISTENER_59:any[];
  __DataResolver_60:import34.DataResolver;
  constructor(parent:import35.Injector) {
    super(parent,[
      import36.HomeComponentNgFactory,
      import37.AboutComponentNgFactory,
      import38.NoContentComponentNgFactory,
      import39.AppComponentNgFactory
    ]
    ,[import39.AppComponentNgFactory]);
  }
  get _LOCALE_ID_23():any {
    if ((this.__LOCALE_ID_23 == null)) { (this.__LOCALE_ID_23 = import3._localeFactory(this.parent.get(import40.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_23;
  }
  get _NgLocalization_24():import18.NgLocaleLocalization {
    if ((this.__NgLocalization_24 == null)) { (this.__NgLocalization_24 = new import18.NgLocaleLocalization(this._LOCALE_ID_23)); }
    return this.__NgLocalization_24;
  }
  get _Compiler_25():import19.Compiler {
    if ((this.__Compiler_25 == null)) { (this.__Compiler_25 = new import19.Compiler()); }
    return this.__Compiler_25;
  }
  get _APP_ID_26():any {
    if ((this.__APP_ID_26 == null)) { (this.__APP_ID_26 = import41._appIdRandomProviderFactory()); }
    return this.__APP_ID_26;
  }
  get _DOCUMENT_27():any {
    if ((this.__DOCUMENT_27 == null)) { (this.__DOCUMENT_27 = import4._document()); }
    return this.__DOCUMENT_27;
  }
  get _HAMMER_GESTURE_CONFIG_28():import20.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_28 == null)) { (this.__HAMMER_GESTURE_CONFIG_28 = new import20.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_28;
  }
  get _EVENT_MANAGER_PLUGINS_29():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_29 == null)) { (this.__EVENT_MANAGER_PLUGINS_29 = [
      new import42.DomEventsPlugin(),
      new import43.KeyEventsPlugin(),
      new import20.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_28)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_29;
  }
  get _EventManager_30():import21.EventManager {
    if ((this.__EventManager_30 == null)) { (this.__EventManager_30 = new import21.EventManager(this._EVENT_MANAGER_PLUGINS_29,this.parent.get(import44.NgZone))); }
    return this.__EventManager_30;
  }
  get _DomSharedStylesHost_31():import22.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_31 == null)) { (this.__DomSharedStylesHost_31 = new import22.DomSharedStylesHost(this._DOCUMENT_27)); }
    return this.__DomSharedStylesHost_31;
  }
  get _AnimationDriver_32():any {
    if ((this.__AnimationDriver_32 == null)) { (this.__AnimationDriver_32 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_32;
  }
  get _DomRootRenderer_33():import23.DomRootRenderer_ {
    if ((this.__DomRootRenderer_33 == null)) { (this.__DomRootRenderer_33 = new import23.DomRootRenderer_(this._DOCUMENT_27,this._EventManager_30,this._DomSharedStylesHost_31,this._AnimationDriver_32,this._APP_ID_26)); }
    return this.__DomRootRenderer_33;
  }
  get _NgProbeToken_34():any[] {
    if ((this.__NgProbeToken_34 == null)) { (this.__NgProbeToken_34 = [import8.routerNgProbeToken()]); }
    return this.__NgProbeToken_34;
  }
  get _RootRenderer_35():any {
    if ((this.__RootRenderer_35 == null)) { (this.__RootRenderer_35 = import45._createConditionalRootRenderer(this._DomRootRenderer_33,this.parent.get(import45.NgProbeToken,(null as any)),this._NgProbeToken_34)); }
    return this.__RootRenderer_35;
  }
  get _DomSanitizer_36():import24.DomSanitizerImpl {
    if ((this.__DomSanitizer_36 == null)) { (this.__DomSanitizer_36 = new import24.DomSanitizerImpl()); }
    return this.__DomSanitizer_36;
  }
  get _Sanitizer_37():any {
    if ((this.__Sanitizer_37 == null)) { (this.__Sanitizer_37 = this._DomSanitizer_36); }
    return this.__Sanitizer_37;
  }
  get _AnimationQueue_38():import25.AnimationQueue {
    if ((this.__AnimationQueue_38 == null)) { (this.__AnimationQueue_38 = new import25.AnimationQueue(this.parent.get(import44.NgZone))); }
    return this.__AnimationQueue_38;
  }
  get _ViewUtils_39():import26.ViewUtils {
    if ((this.__ViewUtils_39 == null)) { (this.__ViewUtils_39 = new import26.ViewUtils(this._RootRenderer_35,this._Sanitizer_37,this._AnimationQueue_38)); }
    return this.__ViewUtils_39;
  }
  get _IterableDiffers_40():any {
    if ((this.__IterableDiffers_40 == null)) { (this.__IterableDiffers_40 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_40;
  }
  get _KeyValueDiffers_41():any {
    if ((this.__KeyValueDiffers_41 == null)) { (this.__KeyValueDiffers_41 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_41;
  }
  get _SharedStylesHost_42():any {
    if ((this.__SharedStylesHost_42 == null)) { (this.__SharedStylesHost_42 = this._DomSharedStylesHost_31); }
    return this.__SharedStylesHost_42;
  }
  get _Title_43():import27.Title {
    if ((this.__Title_43 == null)) { (this.__Title_43 = new import27.Title()); }
    return this.__Title_43;
  }
  get _RadioControlRegistry_44():import28.RadioControlRegistry {
    if ((this.__RadioControlRegistry_44 == null)) { (this.__RadioControlRegistry_44 = new import28.RadioControlRegistry()); }
    return this.__RadioControlRegistry_44;
  }
  get _ROUTER_CONFIGURATION_45():any {
    if ((this.__ROUTER_CONFIGURATION_45 == null)) { (this.__ROUTER_CONFIGURATION_45 = {
      useHash: true,
      preloadingStrategy: import33.PreloadAllModules
    }
    ); }
    return this.__ROUTER_CONFIGURATION_45;
  }
  get _LocationStrategy_46():any {
    if ((this.__LocationStrategy_46 == null)) { (this.__LocationStrategy_46 = import8.provideLocationStrategy(this.parent.get(import46.PlatformLocation),this.parent.get(import47.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_45)); }
    return this.__LocationStrategy_46;
  }
  get _Location_47():import29.Location {
    if ((this.__Location_47 == null)) { (this.__Location_47 = new import29.Location(this._LocationStrategy_46)); }
    return this.__Location_47;
  }
  get _UrlSerializer_48():import30.DefaultUrlSerializer {
    if ((this.__UrlSerializer_48 == null)) { (this.__UrlSerializer_48 = new import30.DefaultUrlSerializer()); }
    return this.__UrlSerializer_48;
  }
  get _RouterOutletMap_49():import31.RouterOutletMap {
    if ((this.__RouterOutletMap_49 == null)) { (this.__RouterOutletMap_49 = new import31.RouterOutletMap()); }
    return this.__RouterOutletMap_49;
  }
  get _NgModuleFactoryLoader_50():import32.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_50 == null)) { (this.__NgModuleFactoryLoader_50 = new import32.SystemJsNgModuleLoader(this._Compiler_25,this.parent.get(import32.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_50;
  }
  get _ROUTES_51():any[] {
      if ((this.__ROUTES_51 == null)) { (this.__ROUTES_51 = [[
        {
          path: '',
          component: import48.HomeComponent
        }
        ,
        {
          path: 'home',
          component: import48.HomeComponent
        }
        ,
        {
          path: 'about',
          component: import49.AboutComponent
        }
        ,
        {
          path: 'detail',
          loadChildren: './+detail#DetailModule'
        }
        ,
        {
          path: 'barrel',
          loadChildren: './+barrel#BarrelModule'
        }
        ,
        {
          path: '**',
          component: import50.NoContentComponent
        }

      ]
    ]); }
    return this.__ROUTES_51;
  }
  get _Router_52():any {
    if ((this.__Router_52 == null)) { (this.__Router_52 = import8.setupRouter(this._ApplicationRef_20,this._UrlSerializer_48,this._RouterOutletMap_49,this._Location_47,this,this._NgModuleFactoryLoader_50,this._Compiler_25,this._ROUTES_51,this._ROUTER_CONFIGURATION_45,this.parent.get(import51.UrlHandlingStrategy,(null as any)),this.parent.get(import52.RouteReuseStrategy,(null as any)))); }
    return this.__Router_52;
  }
  get _ActivatedRoute_53():any {
    if ((this.__ActivatedRoute_53 == null)) { (this.__ActivatedRoute_53 = import8.rootRoute(this._Router_52)); }
    return this.__ActivatedRoute_53;
  }
  get _NoPreloading_57():import33.NoPreloading {
    if ((this.__NoPreloading_57 == null)) { (this.__NoPreloading_57 = new import33.NoPreloading()); }
    return this.__NoPreloading_57;
  }
  get _ROUTER_INITIALIZER_58():any {
    if ((this.__ROUTER_INITIALIZER_58 == null)) { (this.__ROUTER_INITIALIZER_58 = import8.initialRouterNavigation(this._Router_52,this._ApplicationRef_20,this._RouterPreloader_56,this._ROUTER_CONFIGURATION_45)); }
    return this.__ROUTER_INITIALIZER_58;
  }
  get _APP_BOOTSTRAP_LISTENER_59():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_59 == null)) { (this.__APP_BOOTSTRAP_LISTENER_59 = [this._ROUTER_INITIALIZER_58]); }
    return this.__APP_BOOTSTRAP_LISTENER_59;
  }
  get _DataResolver_60():import34.DataResolver {
    if ((this.__DataResolver_60 == null)) { (this.__DataResolver_60 = new import34.DataResolver()); }
    return this.__DataResolver_60;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import53.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._ErrorHandler_8 = import4.errorHandler();
    this._BrowserXhr_9 = new import9.BrowserXhr();
    this._ResponseOptions_10 = new import10.BaseResponseOptions();
    this._XSRFStrategy_11 = import7._createDefaultCookieXSRFStrategy();
    this._XHRBackend_12 = new import11.XHRBackend(this._BrowserXhr_9,this._ResponseOptions_10,this._XSRFStrategy_11);
    this._RequestOptions_13 = new import12.BaseRequestOptions();
    this._Http_14 = import7.httpFactory(this._XHRBackend_12,this._RequestOptions_13);
    this._AppConfig_15 = new import13.AppConfig(this._Http_14);
    this._APP_INITIALIZER_16 = [import13.configServiceFactory(this._AppConfig_15)];
    this._ApplicationInitStatus_17 = new import14.ApplicationInitStatus(this._APP_INITIALIZER_16);
    this._Testability_18 = new import15.Testability(this.parent.get(import44.NgZone));
    this._ApplicationRef__19 = new import16.ApplicationRef_(this.parent.get(import44.NgZone),this.parent.get(import54.Console),this,this._ErrorHandler_8,this,this._ApplicationInitStatus_17,this.parent.get(import15.TestabilityRegistry,(null as any)),this._Testability_18);
    this._ApplicationRef_20 = this._ApplicationRef__19;
    this._AppState_21 = new import17.AppState();
    this._AppModule_22 = new import1.AppModule(this._ApplicationRef_20,this._AppState_21);
    this._PreloadAllModules_54 = new import33.PreloadAllModules();
    this._PreloadingStrategy_55 = this._PreloadAllModules_54;
    this._RouterPreloader_56 = new import33.RouterPreloader(this._Router_52,this._NgModuleFactoryLoader_50,this._Compiler_25,this,this._PreloadingStrategy_55);
    return this._AppModule_22;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import55.ErrorHandler)) { return this._ErrorHandler_8; }
    if ((token === import9.BrowserXhr)) { return this._BrowserXhr_9; }
    if ((token === import10.ResponseOptions)) { return this._ResponseOptions_10; }
    if ((token === import56.XSRFStrategy)) { return this._XSRFStrategy_11; }
    if ((token === import11.XHRBackend)) { return this._XHRBackend_12; }
    if ((token === import12.RequestOptions)) { return this._RequestOptions_13; }
    if ((token === import57.Http)) { return this._Http_14; }
    if ((token === import13.AppConfig)) { return this._AppConfig_15; }
    if ((token === import14.APP_INITIALIZER)) { return this._APP_INITIALIZER_16; }
    if ((token === import14.ApplicationInitStatus)) { return this._ApplicationInitStatus_17; }
    if ((token === import15.Testability)) { return this._Testability_18; }
    if ((token === import16.ApplicationRef_)) { return this._ApplicationRef__19; }
    if ((token === import16.ApplicationRef)) { return this._ApplicationRef_20; }
    if ((token === import17.AppState)) { return this._AppState_21; }
    if ((token === import1.AppModule)) { return this._AppModule_22; }
    if ((token === import40.LOCALE_ID)) { return this._LOCALE_ID_23; }
    if ((token === import18.NgLocalization)) { return this._NgLocalization_24; }
    if ((token === import19.Compiler)) { return this._Compiler_25; }
    if ((token === import41.APP_ID)) { return this._APP_ID_26; }
    if ((token === import58.DOCUMENT)) { return this._DOCUMENT_27; }
    if ((token === import20.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_28; }
    if ((token === import21.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_29; }
    if ((token === import21.EventManager)) { return this._EventManager_30; }
    if ((token === import22.DomSharedStylesHost)) { return this._DomSharedStylesHost_31; }
    if ((token === import59.AnimationDriver)) { return this._AnimationDriver_32; }
    if ((token === import23.DomRootRenderer)) { return this._DomRootRenderer_33; }
    if ((token === import16.NgProbeToken)) { return this._NgProbeToken_34; }
    if ((token === import60.RootRenderer)) { return this._RootRenderer_35; }
    if ((token === import24.DomSanitizer)) { return this._DomSanitizer_36; }
    if ((token === import61.Sanitizer)) { return this._Sanitizer_37; }
    if ((token === import25.AnimationQueue)) { return this._AnimationQueue_38; }
    if ((token === import26.ViewUtils)) { return this._ViewUtils_39; }
    if ((token === import62.IterableDiffers)) { return this._IterableDiffers_40; }
    if ((token === import63.KeyValueDiffers)) { return this._KeyValueDiffers_41; }
    if ((token === import22.SharedStylesHost)) { return this._SharedStylesHost_42; }
    if ((token === import27.Title)) { return this._Title_43; }
    if ((token === import28.RadioControlRegistry)) { return this._RadioControlRegistry_44; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_45; }
    if ((token === import47.LocationStrategy)) { return this._LocationStrategy_46; }
    if ((token === import29.Location)) { return this._Location_47; }
    if ((token === import30.UrlSerializer)) { return this._UrlSerializer_48; }
    if ((token === import31.RouterOutletMap)) { return this._RouterOutletMap_49; }
    if ((token === import64.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_50; }
    if ((token === import65.ROUTES)) { return this._ROUTES_51; }
    if ((token === import53.Router)) { return this._Router_52; }
    if ((token === import66.ActivatedRoute)) { return this._ActivatedRoute_53; }
    if ((token === import33.PreloadAllModules)) { return this._PreloadAllModules_54; }
    if ((token === import33.PreloadingStrategy)) { return this._PreloadingStrategy_55; }
    if ((token === import33.RouterPreloader)) { return this._RouterPreloader_56; }
    if ((token === import33.NoPreloading)) { return this._NoPreloading_57; }
    if ((token === import8.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_58; }
    if ((token === import41.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_59; }
    if ((token === import34.DataResolver)) { return this._DataResolver_60; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__19.ngOnDestroy();
    this._RouterPreloader_56.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);