/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../src/app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../src/app/app.service';
import * as import9 from './app.component.css.ngstyle';
import * as import10 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import15 from '@angular/common/src/pipes/json_pipe';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/router/src/router';
import * as import18 from '@angular/router/src/router_state';
import * as import19 from '@angular/common/src/location/location_strategy';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/router/src/router_outlet_map';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from '@angular/router/src/directives/router_link';
import * as import24 from '@angular/router/src/directives/router_link_active';
import * as import25 from '@angular/router/src/directives/router_outlet';
import * as import26 from '@angular/core/src/security';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.AppState,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import9.styles];
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _RouterLinkWithHref_3_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_3_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_3_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_3_1:import12.QueryList<any>;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _RouterLinkWithHref_6_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_6_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_6_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_6_1:import12.QueryList<any>;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_9_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_9_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_9_1:import12.QueryList<any>;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_12_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_12_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_12_1:import12.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import10.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_15_4:import11.Wrapper_RouterLinkActive;
  _query_RouterLink_15_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import12.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _vc_21:import13.ViewContainer;
  _RouterOutlet_21_5:import14.Wrapper_RouterOutlet;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _arr_65:any;
  _arr_66:any;
  _arr_67:any;
  _arr_68:any;
  _arr_69:any;
  /*private*/ _expr_70:any;
  _pipe_json_0:import15.JsonPipe;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._arr_65 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_66 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_67 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_68 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_69 = import3.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_70 = import16.UNINITIALIZED;
    this._expr_72 = import16.UNINITIALIZED;
    this._expr_73 = import16.UNINITIALIZED;
    this._expr_74 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_3_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import19.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_3_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import20.ElementRef(this._el_3),this.renderer,this.ref);
    this._query_RouterLink_3_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_3_1 = new import12.QueryList<any>();
    this._text_4 = this.renderer.createText(this._el_3,'\n        Index\n      ',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_1,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_6_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import19.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_6_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import20.ElementRef(this._el_6),this.renderer,this.ref);
    this._query_RouterLink_6_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_6_1 = new import12.QueryList<any>();
    this._text_7 = this.renderer.createText(this._el_6,'\n        Home\n      ',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_1,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_9_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import19.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_9_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import20.ElementRef(this._el_9),this.renderer,this.ref);
    this._query_RouterLink_9_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_9_1 = new import12.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'\n        Detail\n      ',(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_1,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_12_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import19.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_12_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import20.ElementRef(this._el_12),this.renderer,this.ref);
    this._query_RouterLink_12_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_12_1 = new import12.QueryList<any>();
    this._text_13 = this.renderer.createText(this._el_12,'\n        Barrel\n      ',(null as any));
    this._text_14 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_1,'a',new import3.InlineArray2(2,'routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_15_3 = new import10.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import17.Router,this.parentIndex),this.parentView.injectorGet(import18.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import19.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_15_4 = new import11.Wrapper_RouterLinkActive(this.parentView.injectorGet(import17.Router,this.parentIndex),new import20.ElementRef(this._el_15),this.renderer,this.ref);
    this._query_RouterLink_15_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import12.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'\n        About\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,parentRenderNode,'main',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n      ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_21 = new import13.ViewContainer(21,19,this,this._el_21);
    this._RouterOutlet_21_5 = new import14.Wrapper_RouterOutlet(this.parentView.injectorGet(import21.RouterOutletMap,this.parentIndex),this._vc_21.vcRef,this.parentView.injectorGet(import22.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_22 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_23 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,parentRenderNode,'pre',new import3.InlineArray2(2,'class','app-state'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,parentRenderNode,'footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'WebPack Angular 2 Starter by ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'@AngularClass',(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_27,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_36,'img',new import3.InlineArray2(2,'width','25%'),(null as any));
    this._text_39 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_34,'\n      ',(null as any));
    this._text_41 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_3,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_3));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_15));
    this._pipe_json_0 = new import15.JsonPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.RouterLinkWithHref) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkWithHref_3_3.context; }
    if (((token === import24.RouterLinkActive) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkActive_3_4.context; }
    if (((token === import23.RouterLinkWithHref) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RouterLinkWithHref_6_3.context; }
    if (((token === import24.RouterLinkActive) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RouterLinkActive_6_4.context; }
    if (((token === import23.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3.context; }
    if (((token === import24.RouterLinkActive) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkActive_9_4.context; }
    if (((token === import23.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    if (((token === import24.RouterLinkActive) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkActive_12_4.context; }
    if (((token === import23.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3.context; }
    if (((token === import24.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4.context; }
    if (((token === import25.RouterOutlet) && (21 === requestNodeIndex))) { return this._RouterOutlet_21_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import16.ValueUnwrapper();
    const currVal_3_0_0:any = this._arr_65('./');
    this._RouterLinkWithHref_3_3.check_routerLink(currVal_3_0_0,throwOnChange,false);
    this._RouterLinkWithHref_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_3_1_0:any = 'active';
    this._RouterLinkActive_3_4.check_routerLinkActive(currVal_3_1_0,throwOnChange,false);
    this._RouterLinkActive_3_4.ngDoCheck(this,this._el_3,throwOnChange);
    const currVal_6_0_0:any = this._arr_66('./home');
    this._RouterLinkWithHref_6_3.check_routerLink(currVal_6_0_0,throwOnChange,false);
    this._RouterLinkWithHref_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_6_1_0:any = 'active';
    this._RouterLinkActive_6_4.check_routerLinkActive(currVal_6_1_0,throwOnChange,false);
    this._RouterLinkActive_6_4.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_9_0_0:any = this._arr_67('./detail');
    this._RouterLinkWithHref_9_3.check_routerLink(currVal_9_0_0,throwOnChange,false);
    this._RouterLinkWithHref_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = 'active';
    this._RouterLinkActive_9_4.check_routerLinkActive(currVal_9_1_0,throwOnChange,false);
    this._RouterLinkActive_9_4.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_12_0_0:any = this._arr_68('./barrel');
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_12_0_0,throwOnChange,false);
    this._RouterLinkWithHref_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = 'active';
    this._RouterLinkActive_12_4.check_routerLinkActive(currVal_12_1_0,throwOnChange,false);
    this._RouterLinkActive_12_4.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_15_0_0:any = this._arr_69('./about');
    this._RouterLinkWithHref_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLinkWithHref_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'active';
    this._RouterLinkActive_15_4.check_routerLinkActive(currVal_15_1_0,throwOnChange,false);
    this._RouterLinkActive_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    this._RouterOutlet_21_5.ngDoCheck(this,this._el_21,throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_3_0.dirty) {
        this._query_RouterLink_3_0.reset(([] as any[]));
        this._RouterLinkActive_3_4.context.links = this._query_RouterLink_3_0;
        this._query_RouterLink_3_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_3_1.dirty) {
        this._query_RouterLinkWithHref_3_1.reset([this._RouterLinkWithHref_3_3.context]);
        this._RouterLinkActive_3_4.context.linksWithHrefs = this._query_RouterLinkWithHref_3_1;
        this._query_RouterLinkWithHref_3_1.notifyOnChanges();
      }
      if (this._query_RouterLink_6_0.dirty) {
        this._query_RouterLink_6_0.reset(([] as any[]));
        this._RouterLinkActive_6_4.context.links = this._query_RouterLink_6_0;
        this._query_RouterLink_6_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_6_1.dirty) {
        this._query_RouterLinkWithHref_6_1.reset([this._RouterLinkWithHref_6_3.context]);
        this._RouterLinkActive_6_4.context.linksWithHrefs = this._query_RouterLinkWithHref_6_1;
        this._query_RouterLinkWithHref_6_1.notifyOnChanges();
      }
      if (this._query_RouterLink_9_0.dirty) {
        this._query_RouterLink_9_0.reset(([] as any[]));
        this._RouterLinkActive_9_4.context.links = this._query_RouterLink_9_0;
        this._query_RouterLink_9_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_9_1.dirty) {
        this._query_RouterLinkWithHref_9_1.reset([this._RouterLinkWithHref_9_3.context]);
        this._RouterLinkActive_9_4.context.linksWithHrefs = this._query_RouterLinkWithHref_9_1;
        this._query_RouterLinkWithHref_9_1.notifyOnChanges();
      }
      if (this._query_RouterLink_12_0.dirty) {
        this._query_RouterLink_12_0.reset(([] as any[]));
        this._RouterLinkActive_12_4.context.links = this._query_RouterLink_12_0;
        this._query_RouterLink_12_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_12_1.dirty) {
        this._query_RouterLinkWithHref_12_1.reset([this._RouterLinkWithHref_12_3.context]);
        this._RouterLinkActive_12_4.context.linksWithHrefs = this._query_RouterLinkWithHref_12_1;
        this._query_RouterLinkWithHref_12_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset(([] as any[]));
        this._RouterLinkActive_15_4.context.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3.context]);
        this._RouterLinkActive_15_4.context.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_3_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_9_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_12_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_3_3.checkHost(this,this,this._el_3,throwOnChange);
    this._RouterLinkWithHref_6_3.checkHost(this,this,this._el_6,throwOnChange);
    this._RouterLinkWithHref_9_3.checkHost(this,this,this._el_9,throwOnChange);
    this._RouterLinkWithHref_12_3.checkHost(this,this,this._el_12,throwOnChange);
    this._RouterLinkWithHref_15_3.checkHost(this,this,this._el_15,throwOnChange);
    valUnwrapper.reset();
    const currVal_70:any = import3.inlineInterpolate(1,'this.appState.state = ',valUnwrapper.unwrap(this._pipe_json_0.transform(this.context.appState.state)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_70,currVal_70))) {
      this.renderer.setText(this._text_25,currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_72:any = this.context.url;
    if (import3.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementProperty(this._el_31,'href',this.viewUtils.sanitizer.sanitize(import26.SecurityContext.URL,currVal_72));
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = this.context.url;
    if (import3.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementProperty(this._el_36,'href',this.viewUtils.sanitizer.sanitize(import26.SecurityContext.URL,currVal_73));
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = this.context.angularclassLogo;
    if (import3.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementProperty(this._el_38,'src',this.viewUtils.sanitizer.sanitize(import26.SecurityContext.URL,currVal_74));
      this._expr_74 = currVal_74;
    }
  }
  destroyInternal():void {
    this._vc_21.destroyNestedViews();
    this._RouterLinkWithHref_3_3.ngOnDestroy();
    this._RouterLinkActive_3_4.ngOnDestroy();
    this._RouterLinkWithHref_6_3.ngOnDestroy();
    this._RouterLinkActive_6_4.ngOnDestroy();
    this._RouterLinkWithHref_9_3.ngOnDestroy();
    this._RouterLinkActive_9_4.ngOnDestroy();
    this._RouterLinkWithHref_12_3.ngOnDestroy();
    this._RouterLinkActive_12_4.ngOnDestroy();
    this._RouterLinkWithHref_15_3.ngOnDestroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this._RouterOutlet_21_5.ngOnDestroy();
  }
  handleEvent_3(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_3_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_6_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_9_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_12_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_15_3.handleEvent(eventName,$event) && result);
    return result;
  }
}